### ISSUE TITLE
Adding a Nazi merchant to C3M6_A

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#285]
What do you guys think about a Nazi merchant that can be added to C3M6_A that wants wo share equipment in favor of gold before he flees to Argentina?

We would need some scripts, a dialogue, a sprite set (one-directional) and a place where to put himm (maybe before the Wolfenstein entrance) but that way collecting coins before the final map would make sense.

**Comment by Ozymandias81** [comment]
Sprites are already in WIP by @DoomJedi , just to let you know.

**Comment by DoomJedi** [comment]
Prepared the sprites.

**Comment by Ozymandias81** [comment]
[Added](https://github.com/Realm667/WolfenDoom/commit/3a2eb728c62ad1e8641d23d99cc4784a1e5150dc) sprites and coded actor, also included mugshots as well.

**Comment by Username-N00b-is-not-available** [comment]
The idea is very nice. The problem is what would he offer? There is enough ammo in the levels, most (or all?) weapons are available to the player, and the encounters are pretty balanced overall.
Armor? Powerups, maybe? If yes, then which ones? A sort of map which helps navigating through M6_B (we can also include a specific style for the automap in this case)? Exclusive weapons? MP40/I, StG 44, MG 42, FG 42, M30 Luftwaffe? Something Zyklon?
Maybe from him we could buy keys to a super-secret passage to an arena with very tough fights, or to a hall of Wolfenstein references, or to another easter-egg, or to a developer room similar to Q2-style?
</ ramblings>

**Comment by Tormentor667** [comment]
He'd offer armor, powerups and health pickups. He simply takes the same role as Laz in the intermap, as somehow you need a change to use your treasure loot for something useful :)

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 Just in case I would like to reiterate that in the later levels resources are abundant, and with more-or-less 'usual' shop offers his presence would add nothing to the game. The player enters the level loaded for bear (you can watch this in my videos which I am about to finish uploading :-D ); they have all weapons except the Panzerschreck and secret ones, and lots of inventory items and ammo.
Also, if this person sells regular goods, why not add similar characters to C1 and C2 then?
I'm starting to think more of the possibility of him selling a key to a secret passage to a Doom Eternal-style arena with lots of zombies to gather even more souls before the final battle.

**Comment by Tormentor667** [comment]
This is something I find interesting in addition to the regular items he can buy - a key for a zombie chamber

**Comment by Username-N00b-is-not-available** [comment]
What about FG 42? :D

**Comment by Tormentor667** [comment]
No additional weapons :)

**Comment by DoomJedi** [comment]
In my "No Man's Land" mod (where I took merchant visual concept from) we had not only "smuggler" (this is how he was called there, much more widely useful term IMHO) to buy stuff, but also "con artist" you could indeed buy special keys from (also pimps and hookers btw). So this is good idea, keys are part of his visual design anyway, as are documents (nazi passports or important nazi documents) you can buy, medals and even grenades.
Such characters can be useful in other maps, to supply unique stuff were needed. Especially if put in secret areas. We can make more variants of the base character.

P. S. ....Maybe he can open left or right side of his coat depending of what you show interest in buying. Just a thought.

**Comment by Username-N00b-is-not-available** [comment]
@Ozymandias81 It is possible with ACS, for example you can tie some scripts to dialogue options similarly to how I did it in my first version of C3M5_A surrendering soldier. The scripts would use the SetActorState function.

**Comment by Ozymandias81** [comment]
@Username-N00b-is-not-available would you mind to apply those scripts then? I need to concentrate fixing maps which is already very tedious, so some little help onto this merchant thing would be welcome :smile:

**Comment by Username-N00b-is-not-available** [comment]
@Ozymandias81, sorry but I have a very miniscule amount of free time now, I have added the merchant lines to the string table instead. The animation can be changed in the following way.

Dialogue:
```
    ...
    page //number 1941
    {
         name = "Fritz Hosenscheisser";
         dialog = "What do you want?";
         choice
         {
             text = "Ammo.";
             special = 80; //ACS_Execute
             arg0str = "Hosenscheisser_Animate"; //or arg0 and a script number if it does not work
             arg1 = 1; //ammo
             nextpage = 1942; //ammo page
         }
         choice
         {
             text = "Medicine.";
             special = 80;
             arg0str = "Hosenscheisser_Animate";
             arg1 = 2; //medicine
             nextpage = 1943;
         }
        ...
    }
    page //Ammo, number 1942
    {
         name = "Fritz Hosenscheisser";
         dialog = "Ammo? Here's some ammo for you...";
         choice
         {
             text = "9mm ammo.";
             //usual shop setup here
         }
         choice
         {
             text = "I need something else.";
             special = 80;
             arg0str = "Hosenscheisser_Animate";
             arg1 = 0; //introductory animation
             nextpage = 1941;
         }
        ...
    }
```

ACS:
```
Script "Hosenscheisser_Animate" (int page) {
    int hosenscheisser_tid = 1234;
    if (page == 0) SetActorState(hosenscheisser_tid, "SeeAround");
    else if (page == 1) SetActorState(hosenscheisser_tid, "SellLeft");
    else if (page == 2) SetActorState(hosenscheisser_tid, "SellRight");
    ...
}
```

**Comment by Ozymandias81** [comment]
Well just implemented now the new script, Arg0str and Arg1 or higher are not supported, so I had to create separate scripts for each state change. Going to commit right now, thanks for the help. I even adjusted mugshots used, we still need fitting dialogues.

**Comment by Tormentor667** [comment]
Do you mean "fitting dialogues" for what you can buy from him? The introduction dialogues are set already by me and improved by @Talon1024

**Comment by Ozymandias81** [comment]
The comment was edit before my second commit for it, didn't notice it had already dialogues... we need the map object and the suspicious key though yet.

**Comment by Tormentor667** [comment]
What suspicious key? What objective?

**Comment by Username-N00b-is-not-available** [comment]
It looks like you are talking about two different actors, @Ozymandias81 about Hosenscheisser, and @Tormentor667 about Johansen.
@Tormentor667 Some days ago I wrote a draft of Hosenscheisser dialogues (around line 1550). Along with the usual items I would like him to sell a map of C3M6_B (I think instead of a powerup similar to Doom's Computer Area Map it would be better to include a high-resolution image of a map printed on paper, so it could be activated from the inventory, just like Keen safe code notes), and also a key for a secret zombie chamber hidden somewhere in the castle <strike>the necessity of which has always been mentioned by the Bolsheviks</strike>.
All this is of course not final, if you do not want 'special items' to be sold by him anymore, they can be removed.

**Comment by Tormentor667** [comment]
I like your approach here for the Hosenscheisser additions, this is awesome input, please do that :) 

For Mikkel in Iceland, what do you suggest here? We can also place him on C2M6_B by the way in some wilderness place.

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 I think we can move him just a bit, into a small 'compartment' around (11957, 16025) connected to the main area from the east with a not very obvious passage.
The special offers are harder to think about. A map would be useless. Maybe a backpack, but it is already available during normal play; the player can use the encounter as the last opportunity to get it if they missed it. Selling Panzerschreck rockets would completely trivialize the flying piggy fight, this would be a problem. A good idea would be to sell a minesweeper if the player wants to backtrack to get supplies from the area near (5426, 6286). Again, at this point the player has full inventory, and we have closely to nothing to offer them... <strike>except the KDiZD Z1M10 super-powerup</strike>

**Comment by Tormentor667** [comment]
Well, I could imagine selling regular inventory stuff, mostly ammunition for the more powerful weapons for instance, health kits, armory, stuff that makes proceeding the map easier.

**Comment by DoomJedi** [comment]
Based on the pic - you can sell him grenades...always useful, health...

**Comment by Tormentor667** [comment]
Agreed, grenades are always good.

**Comment by Username-N00b-is-not-available** [comment]
No one disputes that, we should definitely add grenades, but in my post I was talking about some special offers. Ammo for the powerful weapons as suggested by @Tormentor667 should do good, of them I suggest adding rifle bullets and petrol to the offer list (but on a high price, since it makes short work of the boss).
Oh, I know, he might also heal the player! Just like Lt. Halderman, but for money.

**Comment by Tormentor667** [comment]
So here is a quick list now:

- Grenades
- Gas (for the Flamer)
- Bullets (for the Rifle)
- Full Healing (as Halderman, just for a high price)
- Armor (200% one)
- Field Kits

Anything special for the C2 merchant like the map for Castle Wolfenstein in C3?

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 I still have no ideas for C2 merchant special items... If neither do you, it could be the time to implement these.

**Comment by Tormentor667** [comment]
I will change the position a bit, fix it and make it less obvious. Regarding the objects, I think you can take these and we are ready with it. Can you take care?

-  Grenades
-  Gas (for the Flamer)
-  Bullets (for the Rifle)
-  Full Healing (as Halderman, just for a high price)
-  Armor (200% one)
-  Field Kits
-  Minesweeper

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 Yes, I'll probably try adding this in the next few days.

**Comment by Tormentor667** [comment]
Perfect, thanks kindly :)

**Comment by Username-N00b-is-not-available** [comment]
Done this for Mikkel in https://github.com/Realm667/WolfenDoom/commit/4004829996fe0335b644adec1a5e28f8d956fde4.
The issue can not be closed yet, we should implement the C3M6_B area map and the zombie chamber.

**Comment by Tormentor667** [comment]
Sorry if I sound too dumb, but can you exactly tell me what you need when you say "an area map for C3M6_B". Regarding the zombie chamber, I am not sure if C3M6_B is the right place for this. We already have a skull-key down there. What about selling the player a key that opens a door in the excavation in C3M6_A instead full oz zombies (and souls)?

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 Sure. I wanted something like [this](https://cdn.jhmrad.com/wp-content/uploads/medieval-castle-floor-plans-designs-plan-frompo_112555.jpg), but for the entire C3M6_B map (minus secret areas). The design choice is fully up to you. This may be very tough to do, not sure if it will be worth it...
Yes, why not, in M6_A it would be nice too. Then the story of Fritz would be more believable: he simply searched the wrong place! As for the chamber itself, I think it should offer something different from just cleaning the room and taking souls as trophies; we can make something like the breaking wooden floor area in C3M3_A, but with waves of zombies you have to survive like in C3M4, albeit on a lower scale (with no additional resources spawned during the battle!)

**Comment by Tormentor667** [comment]
@Username-N00b-is-not-available I am done with the map, still have the open files if we want to change things but I think it works as is ( https://github.com/Realm667/WolfenDoom/commit/53a932e89c2d9df528c4ca4088692c0ffcdabee1 ).

Can you also please add a skull key to the merchant? I will add the functionality to C3M6_A then with the Zombie ambush for the player as soon as you are done.

**Comment by Username-N00b-is-not-available** [comment]
Added both the key and the plan. The plan design is really good, but could you @Tormentor667 please upload a more high-res version of it? The text is barely visible to me.

**Comment by Tormentor667** [comment]
Hires version is online. Will add the zombie area to C3M6_B this evening

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 Do you mean M6_A?

**Comment by Tormentor667** [comment]
Done with both NPCs, nothing more to add here.
