### ISSUE TITLE
C3M6_A: Buying the Wolfenstein map from the smuggler doesn't work

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#419]
You can buy it but it doesn't appear in your inventory.

**Comment by AFADoomer** [comment]
I thought I fixed this a while ago...  Just tested, and it shows up in the usable item inventory list and works for me.

**Comment by Username-N00b-is-not-available** [comment]
@AFADoomer This is what happens for me (video): [hosenscheisser.zip](https://github.com/Realm667/WolfenDoom/files/6096790/hosenscheisser.zip)
You can buy several maps, and all will end up in the inventory. Must be something with HandlePickup or related methods.
***
You can also spend all your money on the suspicious keys, but there will only be one in your inventory. Only one key is needed for progress.

**Comment by Tormentor667** [comment]
This is extremely strange then. I was doing a full playthrough from the start where this happened. The money gets removed but the map isn’t appearing in the inventory.

When was this fixed? I started my full C3 playthrough about 2 weeks ago and didn’t update my build since then (sans for the parachute sequence).

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 This is not fixed, there is still a bug :-)
I have nearly the same situation as you: I started C3 in late February and ended C3M6_B on 04 Mar. Then I updated my .pk3, and because there were no geometry or ACS changes, the savegame from C3M6_A still worked today (for the video). I saved exactly before Hosenscheisser 'just in case', because I remembered this problem, and, well, the savegame proved useful.
IIRC the behaviour was exactly the same on the old build when I played the map on 04 Mar.

**Comment by Tormentor667** [comment]
Thanks for confirmation

**Comment by AFADoomer** [comment]
The problem with it not being placed in your inventory was fixed in 11bd9db6ef594f804295ba6ef9be0d315e547e17.

We might still need to fix the max amounts for both the map and the suspicious key so that you can only buy one of each.

**Comment by Tormentor667** [comment]
> The problem with it not being placed in your inventory was fixed in [11bd9db](https://github.com/Realm667/WolfenDoom/commit/11bd9db6ef594f804295ba6ef9be0d315e547e17) (27 Feb).

That's very good, then it simply interfers with my current testing build. Thanks for clarifying.

**Comment by AFADoomer** [comment]
The issue of being able to buy multiple maps and keys should also be fixed as of a015900bfd78c76079e2aefd234ebc233793b4f0.
