### ISSUE TITLE
Enemy count is wrong

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#546]
In c3m5_c, i've killed all enemies (I think), but the enemy count is wrong. It says: 106/79....

![Screenshot_Doom_20210430_151252](https://user-images.githubusercontent.com/77861029/116710915-956b5e00-a9d2-11eb-8b6c-b51a91bb073d.png)

**Comment by Tormentor667** [comment]
Were alarm panels involved?

**Comment by x3003** [comment]
I think just 1 or 2. The rest was taken out ;)

**Comment by Username-N00b-is-not-available** [comment]
Such problems have been always present on stealth maps, I had reported them multiple times. Lots of measures were done every time, but here we are again... I very much doubt something this could be reliably fixed in a few hours span, so this will be left to 3.1.

**Comment by x3003** [comment]
Oh, it's a minor issue for sure, so don't hurry. But atleast someone should know about it.

**Comment by AFADoomer** [comment]
I think I know what's going on here, but, yes, push fixing this to 3.1.

**Comment by x3003** [comment]
It still doesn't work right. When you begin there are 103 enemies. When you've killed them all, there suppost to be only 87 ??? Of which I killed 105 of them.... A few times the alarm was raised, but it was dealt with....

![Screenshot_Doom_20210501_215802](https://user-images.githubusercontent.com/77861029/116793726-b31aef00-aac8-11eb-8331-c51f821ec5ec.png)

![Screenshot_Doom_20210501_214823](https://user-images.githubusercontent.com/77861029/116793737-d180ea80-aac8-11eb-8ed0-fa9f859dddb7.png)

**Comment by Wolfenburger** [comment]
> Such problems have been always present on stealth maps, I had reported them multiple times. Lots of measures were done every time, but here we are again... I very much doubt something this could be reliably fixed in a few hours span, so this will be left to 3.1.

I honestly don't find it a issue truly. If I can complete the mission from point a to b I don't see the count mattering y'know? Also just a heads up I want to apologize for our fight we had awhile ago in March or April.

**Comment by Tormentor667** [comment]
> I honestly don't find it a issue truly. If I can complete the mission from point a to b I don't see the count mattering y'know?

Well, for speedrunners and contestants this might be important if they want a 100% run.

**Comment by Tormentor667** [comment]
@x3003 is this issue still active?

**Comment by Username-N00b-is-not-available** [comment]
During my recent playthrough alarms were raised in two places IIRC, and on M5_C the killcount problem did not happen, so I think we should close this issue.
